### ISSUE TITLE
 Importer.cpp:2308 Input exception thrown: Decimal overflow: value is greater than 10^6 max 100000000 value 2006137300. 

### ISSUE THREAD

**Issue by jieguolove** [heavyai/heavydb#799]
`
heavysql> \memory_summary
HeavyDB Server CPU Memory Summary:
            MAX            USE      ALLOCATED           FREE
   103028.48 MB        0.00 MB        0.00 MB        0.00 MB

HeavyDB Server GPU Memory Summary:
[GPU]            MAX            USE      ALLOCATED           FREE
  [0]    14576.12 MB        0.00 MB        0.00 MB        0.00 MB

heavysql> \cpu
heavysql> \l
Database | Owner
heavyai | admin
information_schema | admin
hblt | admin
heavysql> \t
CUSTOMER_TABLE
DAILYSESSION_TABLE
RAD_DETAIL
heavysql> select count(*) from RAD_DETAIL;
EXPR$0
0
heavysql> \timing
heavysql> select count(*) from RAD_DETAIL;
EXPR$0
0
1 rows returned.
Execution time: 22 ms, Total time: 51 ms
heavysql> help
..> ;
SQL Error: Non-query expression encountered in illegal context
heavysql> COPY RAD_DETAIL from '/var/lib/heavyai/storage/import/sample_datasets/rad_detail.csv';
Result
Loaded: 13663515 recs, Rejected: 0 recs in 7.230000 secs
1 rows returned.
Execution time: 7366 ms, Total time: 7377 ms
heavysql> COPY CUSTOMER_TABLE from '/var/lib/heavyai/storage/import/sample_datasets/customer_table.csv';
Thrift error: No more data to read.
Thrift connection error: No more data to read.
Retrying connection
Thrift error: No more data to read.
Thrift connection error: No more data to read.
Retrying connection
Thrift: Sun Sep 10 13:22:40 2023 TSocket::write_partial() send() <Host: localhost Port: 6274>: Broken pipe
Thrift error: write() send(): Broken pipe
Thrift connection error: write() send(): Broken pipe
Retrying connection
Thrift: Sun Sep 10 13:22:48 2023 TSocket::write_partial() send() <Host: localhost Port: 6274>: Broken pipe
Thrift error: write() send(): Broken pipe
Thrift connection error: write() send(): Broken pipe
Retrying connection
Cannot connect to HeavyDB Server.
heavysql> \memory_summary
Thrift: Sun Sep 10 13:23:23 2023 TSocket::write_partial() send() <Host: localhost Port: 6274>: Broken pipe
Thrift error: write() send(): Broken pipe
Thrift connection error: write() send(): Broken pipe
Retrying connection
Thrift: Sun Sep 10 13:23:25 2023 TSocket::write_partial() send() <Host: localhost Port: 6274>: Broken pipe
Thrift error: write() send(): Broken pipe
Thrift connection error: write() send(): Broken pipe
Retrying connection
Thrift: Sun Sep 10 13:23:29 2023 TSocket::write_partial() send() <Host: localhost Port: 6274>: Broken pipe
Thrift error: write() send(): Broken pipe
Thrift connection error: write() send(): Broken pipe
Retrying connection
^C
Interrupt signal (2) received.
heavyai@node13:~$ exit
logout
root@node13:~# systemctl status heavydb
● heavydb.service - HEAVY.AI HeavyDB database server
     Loaded: loaded (/lib/systemd/system/heavydb.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-09-10 10:33:55 CST; 2h 49min ago
   Main PID: 534788 (heavydb)
      Tasks: 2 (limit: 149999)
     Memory: 1.5G
     CGroup: /system.slice/heavydb.service
             └─534788 [heavydb]

9月 10 13:22:29 node13 heavydb[534788]: [198B blob data]
9月 10 13:22:29 node13 heavydb[534788]: [507B blob data]
9月 10 13:22:29 node13 heavydb[534788]: [468B blob data]
9月 10 13:22:29 node13 heavydb[534788]: [480B blob data]
9月 10 13:22:29 node13 heavydb[534788]: 2023-09-10T13:22:29.597125 E 534788 0 0 Importer.cpp:2308 Input exception thrown: Decimal overflow: value is greater than 10^6 max 100000000 value 2006137300. Ro>
9月 10 13:22:29 node13 heavydb[534788]: [184B blob data]
9月 10 13:22:29 node13 heavydb[534788]: 2023-09-10T13:22:29.596812 E 534788 0 0 Importer.cpp:2308 Input exception thrown: Decimal overflow: value is greater than 10^6 max 100000000 value 2497654900. Ro>
9月 10 13:22:29 node13 heavydb[534788]: [165B blob data]
9月 10 13:22:29 node13 heavydb[534788]: 2023-09-10T13:22:29.596733 E 534788 0 0 Importer.cpp:2308 Input exception thrown: Decimal overflow: value is greater than 10^6 max 100000000 value 861866800. Row>
9月 10 13:22:29 node13 heavydb[534788]: [163B blob data]
root@node13:~# su - heavyai 
heavyai@node13:~$ heavysql -p admin
Thrift: Sun Sep 10 13:23:49 2023 TSocket::open() connect() <Host: localhost Port: 6274>: Connection refused
Failed to open transport. Is heavydb running?
heavyai@node13:~$ exit
logout
root@node13:~# systemctl stop heavydb
`

**Comment by jieguolove** [comment]
I want to migrate data from an Oracle database to a HeavyDB. Are there any recommendations for mapping between the Oracle table field types and the HeavyDB field types?

**Comment by jieguolove** [comment]
I have resolved the error. The basic reference for table field types is as follows: 
1.NUMBER is modified to DECIMAL, where the format of DECIMAL is DECIMAL(number, precision). For example, NUMBER(8) is modified to DECIMAL(8,0), and NUMBER(8,2) is modified to DECIMAL(8,2). 
2.VARCHAR2 is changed to TEXT. 
3.DATE does not need to be modified。
[https://docs.heavy.ai/sql/data-definition-ddl/tables](url)

Is there anything else to add? Thank you.

**Comment by cdessanti** [comment]
When transitioning from Oracle to HeavyDB, optimizing memory allocation becomes crucial. You can achieve this by selecting the appropriate data types and encodings based on the data within your tables.

For instance, consider the handling of dates. If your Oracle source table contains dates without timestamps (e.g., '2023-06-12 00:00:00'), you can use the DATE data type. If your date range falls between April 14, 1880, and September 9, 2059, you can employ an ENCODING of DAYS(16). The '16' indicates the number of bits used per value, allowing you to store dates using just 2 bytes.

On the other hand, if your source columns contain timestamps along with the date (e.g., '2023-06-12 10:23:12') and you need to retain this information, the TIMESTAMP data type is necessary. By default, it consumes 8 bytes, but if your date and time range falls between December 12, 1901, at 20:45:53 and January 19, 2038, at 03:14:07, you can use an ENCODING of FIXED(32) to save 4 bytes.

Now, let's consider the NUMBER data type. In Oracle, the default scale of NUMBER is 38, while in HeavyDB, we are limited to 19 (DECIMAL of BIGINT). Depending on the scale of NUMBER and the values in your tables, you can choose from various types with different precision levels. For example, if you have a NUMBER(4,0) in Oracle with values ranging from -9999 to 9999, you can use SMALLINT or DECIMAL(4,0) with FIXED ENCODING(16), utilizing just 2 bytes. For larger numbers, you can opt for DOUBLE or FLOAT native types, depending on your required precision. Unlike Oracle's NUMBER, HeavyDB supports native data types, allowing you to choose the most suitable one based on your column's values.

Furthermore, you can optimize VARCHAR columns based on their cardinality. For instance, if you have a field containing country names worldwide, you can use a simple TEXT data type. However, since we know that the number of countries is less than 255, it's more efficient to employ an encoding of 8 bits, using just a byte instead of four, without compromising data precision.

To check if a table is utilizing the smallest possible data types, you can run the "\o" command from heavysql after loading the table with a significant number of records. This command provides an optimized DDL for the table (please note that the command is somewhat outdated, but we are actively working on an update). 

As an example, consider a table containing data for various US airports.
```
CREATE TABLE airports (
  iata TEXT ENCODING DICT(32),
  airport_name TEXT ENCODING DICT(32),
  airport_city TEXT ENCODING DICT(32),
  airport_state TEXT ENCODING DICT(32),
  airport_country TEXT ENCODING DICT(32),
  airport_lat FLOAT,
  airport_lon FLOAT)
```
The \o airports command will return an "optimized" DDL depending on the actual contents of the table

```
CREATE TABLE airports (
  iata TEXT ENCODING DICT(16),
  airport_name TEXT ENCODING DICT(16),
  airport_city TEXT ENCODING DICT(16),
  airport_state TEXT ENCODING DICT(8),
  airport_country TEXT ENCODING DICT(8),
  airport_lat FLOAT,
  airport_lon FLOAT)
```
If you need further assistance on this topèic, feel free to ask here or in the community.heavy.ai

Candido

**Comment by jieguolove** [comment]
Thanks a lot!
